import express from 'express';
import dotenv from 'dotenv';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import { connectDB } from './config/db.js';
import authRoutes from './routes/authRoutes.js';
import chatRoutes from './routes/chatRoutes.js';
import { errorHandler, notFound } from './middleware/errorHandler.js';

dotenv.config();
await connectDB();
const app=express();
app.use(cors({origin:process.env.CLIENT_URL?.split(',')||'*'}));
app.use(helmet());
app.use(express.json({limit:'1mb'}));
app.use(morgan('dev'));
app.use('/api',rateLimit({windowMs:15*60*1000,max:200}));
app.get('/api/health',(req,res)=>res.json({status:'ok',service:'prakriti-api'}));
app.use('/api/auth',authRoutes);
app.use('/api/chat',chatRoutes);
app.use('/api/chats',chatRoutes);
app.use(notFound);
app.use(errorHandler);
app.listen(process.env.PORT||5000,()=>console.log('Server running'));
